#Model
https://huggingface.co/Lord769/Models/resolve/main/AniIllustrioussxlv2.safetensors
https://huggingface.co/Lord769/Models/resolve/main/prefectIllustriousXL_v10.safetensors

#Lora
https://huggingface.co/Lord769/Models/resolve/main/AmagiBrilliantPark_SentoIsuzu_IlluXL.safetensors
https://huggingface.co/Lord769/Models/resolve/main/HighSchoolDxDHERO_AsiaArgento_IlluXL.safetensors
https://huggingface.co/Lord769/Models/resolve/main/HighSchoolDxDHERO_HimejimaAkeno_IlluXL.safetensors
https://huggingface.co/Lord769/Models/resolve/main/HighSchoolDxDHERO_PhenexRavel_IlluXL.safetensors
https://huggingface.co/Lord769/Models/resolve/main/HighSchoolDxDHERO_RiasGremory_IlluXL.safetensors
https://huggingface.co/Lord769/Models/resolve/main/HighSchoolDxDHERO_Rossweisse_IlluXL.safetensors
https://huggingface.co/Lord769/Models/resolve/main/HighSchoolDxDHERO_ShidouIrina_IlluXL.safetensors
https://huggingface.co/Lord769/Models/resolve/main/HighSchoolDxDHERO_Yaasaka_IlluXL.safetensors
https://huggingface.co/Lord769/Models/resolve/main/Kakegurui_JabamiYumeko_IlluXL.safetensors
https://huggingface.co/Lord769/Models/resolve/main/MahoukaKoukouNoRettousei_AngelinaKudouShields_IlluXL.safetensors
https://huggingface.co/Lord769/Models/resolve/main/MahoukaKoukouNoRettousei_ChibaErika_IlluXL.safetensors
https://huggingface.co/Lord769/Models/resolve/main/MahoukaKoukouNoRettousei_FujibayashiKyouko_IlluXL.safetensors
https://huggingface.co/Lord769/Models/resolve/main/MahoukaKoukouNoRettousei_YotsubaMaya_IlluXL.safetensors
https://huggingface.co/Lord769/Models/resolve/main/PrincessConnect_Karyl_IlluXL.safetensors
https://huggingface.co/Lord769/Models/resolve/main/PrincessConnect_Pecorine_IlluXL.safetensors
https://huggingface.co/Lord769/Models/resolve/main/Roshidere_KimishimaAyano_IlluXL.safetensors
https://huggingface.co/Lord769/Models/resolve/main/Roshidere_KujouAlisaMikhailovna(Alya)_IlluXL.safetensors
https://huggingface.co/Lord769/Models/resolve/main/Roshidere_KujouMariaMikhailovna(Masha)_IlluXL.safetensors
https://huggingface.co/Lord769/Models/resolve/main/Roshidere_MiyamaeNonoa_IlluXL.safetensors
https://huggingface.co/Lord769/Models/resolve/main/Roshidere_SuouYuki_IlluXL.safetensors
https://huggingface.co/Lord769/Models/resolve/main/SaikyouNoShienshokuWajutsushi_AlmaJudikhali_IlluXL.safetensors
https://huggingface.co/Lord769/Models/resolve/main/SeishunButaYarou_FutabaRio_IlluXL.safetensors
https://huggingface.co/Lord769/Models/resolve/main/SoloLeveling_Gina_IlluXL.safetensors
https://huggingface.co/Lord769/Models/resolve/main/SoloLeveling_HanSemi_IlluXL.safetensors
https://huggingface.co/Lord769/Models/resolve/main/SoloLeveling_ParkHeejin_IlluXL.safetensors
https://huggingface.co/Lord769/Models/resolve/main/SousouNoFrieren_Fern_IlluXL.safetensors
https://huggingface.co/Lord769/Models/resolve/main/SousouNoFrieren_Flamme_IlluXL.safetensors
https://huggingface.co/Lord769/Models/resolve/main/SousouNoFrieren_Ubel_IlluXL.safetensors
https://huggingface.co/Lord769/Models/resolve/main/chisato-lycorecoIL-01.safetensors

#VAE
https://huggingface.co/stabilityai/sdxl-vae/resolve/main/sdxl_vae.safetensors
